ignore: |
  /node_modules/
  /packages/backend/node_modules/
  /packages/web/node_modules/
  /packages/email-template-test-server/node_modules/
  /packages/cli/node_modules/

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  indentation:
    spaces: consistent
    indent-sequences: whatever
    check-multi-line-strings: true
    ignore: |
      .semgrep/rules/**/*.yml
      .semgrep/staging/**/*.yml
