version: "3"

# shared postgres volume so other openstates packages can read the data more consistently
volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  make-tiles:
    build:
      context: .
      args:
        - MAPBOX_ACCESS_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DATABASE_URL
    volumes:
      - ./data:/opt/openstates-district-maps/data
  db:
    image: "mdillon/postgis:11-alpine"
    profiles:
      - db
    hostname: "db"
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: openstates
      POSTGRES_USER: openstates
      POSTGRES_DB: openstatesorg
    volumes:
      - openstates-postgres:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d openstatesorg -U openstates"]
      interval: 10s
      timeout: 5s
      retries: 15
