version: "3"

services:
  make-tiles:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAPBOX_ACCOUNT
        - MAPBOX_ACCESS_TOKEN
        - DATABASE_URL
    volumes:
      - ./data:/opt/openstates-district-maps/data
