name: Alabama
shapefile_urls:
  upper: https://thearp.org/documents/589/AL_SD_Enacted11042021_NR3fNLk.zip
  lower: https://thearp.org/documents/12508/AL_LD_Enacted_Technical_Changes.zip
  congress: https://thearp.org/documents/583/AL_CD_Enacted11042021_QjvUMkL.zip
id-mappings:
  sldl:
    os-id-prefix: "ocd-division/country:us/state:al/sldl:"
    sld-match: 'sldl-010([\d+])'
  sldu:
    os-id-prefix: "ocd-division/country:us/state:al/sldu:"
    sld-match: 'sldu-010([\d+])'
