name: "District of Columbia"
os-id-prefix: "ocd-division/country:us/district:dc"
id-mappings:
  sldu:
    sld-prefix: "ward"
    sld-match: 'sldu-1100(\d)'
  ward:
    sld-match: 'ward-1100(\d)'
  cd:
    sld-match: 'cd-11([\d]+)'
ignored_chambers:
  - sldl
