name: "District of Columbia"
id-mappings:
  sldu:
    os-id-prefix: "ocd-division/country:us/district:dc/ward:"
    sld-match: 'sldu-1100([\d])'
  cd:
    os-id-prefix: "ocd-division/country:us/district:dc"
    sld-match: 'cd-11([\d]+)'
