name: "District of Columbia"
id-mappings:
  sldu:
    key: SLDUST
    os-id-prefix: "ocd-division/country:us/district:dc/ward:"
    sld-match: 'sldu-1100([\d])'
  cd:
    key: SLDUST
    os-id-prefix: "ocd-division/country:us/district:dc/cd:"
