name: Georgia
os-id-prefix: "ocd-division/country:us/state:ga"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-13([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-130([\d]+)'
  cd:
    key: DISTRICT
    sld-match: 'cd-13([\d]+)'
