name: Iowa
shapefile_urls:
  upper: https://thearp.org/documents/715/IA_SD_Enacted11042021.zip
  lower: https://thearp.org/documents/712/IA_LD_Enacted11042021.zip
id-mappings:
  sldl:
    os-id-prefix: "ocd-division/country:us/state:ia/sldl:"
    sld-match: 'sldl-19([\d+])'
  sldu:
    os-id-prefix: "ocd-division/country:us/state:ia/sldu:"
    sld-match: 'sldu-190([\d+])'
