name: Idaho
os-id-prefix: "ocd-division/country:us/state:id"
id-mappings:
  sldl:
    sld-match: 'sldl-160([\d]+)'
    split_districts: true
  sldu:
    sld-match: 'sldu-160([\d]+)'
  cd:
    sld-match: 'cd-160(\d)'
