name: Idaho
os-id-prefix: "ocd-division/country:us/state:id"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-160([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-160([\d]+)'
  cd:
    key: DISTRICT
