name: Illinois
shapefile_urls:
  upper: https://thearp.org/documents/697/Illinois_SD_20210831_Sent_0924_Q2wnnbz.zip
  lower: https://thearp.org/documents/694/Illinois_HD_20210831_sent_0924_Vnk2UaK.zip
id-mappings:
  sldl:
    os-id-prefix: "ocd-division/country:us/state:il/sldl:"
    sld-match: 'sldl-17([\d+])'
  sldu:
    os-id-prefix: "ocd-division/country:us/state:il/sldu:"
    sld-match: 'sldu-170([\d+])'
