name: Louisiana
shapefile_urls:
  upper: https://thearp.org/documents/742/LA_SD_Enacted03092022.zip
  lower: https://thearp.org/documents/739/LA_LD_Enacted03092022.zip
  congress: https://thearp.org/documents/736/LA_CD_Enacted03302022.zip
id-mappings:
  sldl:
    key: "DISTRICT_I"
    os-id-prefix: "ocd-division/country:us/state:la/sldl:"
    sld-match: 'sldl-22([\d]+)'
  sldu:
    key: "DISTRICT_I"
    os-id-prefix: "ocd-division/country:us/state:la/sldu:"
    sld-match: 'sldu-220([\d]+)'
