name: Mississippi
shapefile_urls:
  upper: https://thearp.org/documents/788/MS_SD_Enacted03312022.zip
  lower: https://thearp.org/documents/785/MS_LD_Enacted03312022.zip
  congress: https://thearp.org/documents/782/MS_CD_01242022_Enacted.zip
id-mappings:
  sldl:
    os-id-prefix: "ocd-division/country:us/state:ms/sldl:"
    sld-match: 'sldl-28([\d]+)'
  sldu:
    os-id-prefix: "ocd-division/country:us/state:ms/sldu:"
    sld-match: 'sldu-280([\d]+)'
