name: North Carolina
os-id-prefix: "ocd-division/country:us/state:nc"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-37([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-370([\d]+)'
  cd:
    key: DISTRICT
