name: Nebraska
id-mappings:
  sldu:
    os-id-prefix: "ocd-division/country:us/state:ne/sldu:"
    sld-match: 'sldu-310([\d+])'
shapefile_urls:
  upper: https://thearp.org/documents/814/NE_Upper_Enacted_09302021_GBquMi7.zip
