name: New Hampshire
os-id-prefix: "ocd-division/country:us/state:nh"
id-mappings:
  sldu:
    key: DISTRICT
    sld-match: 'sldu-330([\d]+)'
  sldl:
    key: DISTRICT
    sld-match: 'sldl-330(\d+)'
  cd:
    key: DISTRICT
    sld-match: 'cd-330(\d)'
  custom:
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_1"
      sld-id: sldl-33BE1
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_2"
      sld-id: sldl-33BE2
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_3"
      sld-id: sldl-33BE3
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_4"
      sld-id: sldl-33BE4
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_5"
      sld-id: sldl-33BE5
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_6"
      sld-id: sldl-33BE6
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_7"
      sld-id: sldl-33BE7
    - os-id: "ocd-division/country:us/state:nh/sldl:belknap_8"
      sld-id: sldl-33BE8
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_1"
      sld-id: sldl-33CA1
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_2"
      sld-id: sldl-33CA2
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_3"
      sld-id: sldl-33CA3
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_4"
      sld-id: sldl-33CA4
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_5"
      sld-id: sldl-33CA5
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_6"
      sld-id: sldl-33CA6
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_7"
      sld-id: sldl-33CA7
    - os-id: "ocd-division/country:us/state:nh/sldl:carroll_8"
      sld-id: sldl-33CA8
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_1"
      sld-id: sldl-33CH1
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_2"
      sld-id: sldl-33CH2
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_3"
      sld-id: sldl-33CH3
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_4"
      sld-id: sldl-33CH4
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_5"
      sld-id: sldl-33CH5
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_6"
      sld-id: sldl-33CH6
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_7"
      sld-id: sldl-33CH7
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_8"
      sld-id: sldl-33CH8
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_9"
      sld-id: sldl-33CH9
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_10"
      sld-id: sldl-33CH10
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_11"
      sld-id: sldl-33CH11
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_12"
      sld-id: sldl-33CH12
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_13"
      sld-id: sldl-33CH13
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_14"
      sld-id: sldl-33CH14
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_15"
      sld-id: sldl-33CH15
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_16"
      sld-id: sldl-33CH16
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_17"
      sld-id: sldl-33CH17
    - os-id: "ocd-division/country:us/state:nh/sldl:cheshire_18"
      sld-id: sldl-33CH18
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_1"
      sld-id: sldl-33CO1
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_2"
      sld-id: sldl-33CO2
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_3"
      sld-id: sldl-33CO3
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_4"
      sld-id: sldl-33CO4
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_5"
      sld-id: sldl-33CO5
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_6"
      sld-id: sldl-33CO6
    - os-id: "ocd-division/country:us/state:nh/sldl:coos_7"
      sld-id: sldl-33CO7
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_1"
      sld-id: sldl-33GR1
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_2"
      sld-id: sldl-33GR2
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_3"
      sld-id: sldl-33GR3
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_4"
      sld-id: sldl-33GR4
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_5"
      sld-id: sldl-33GR5
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_6"
      sld-id: sldl-33GR6
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_7"
      sld-id: sldl-33GR7
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_8"
      sld-id: sldl-33GR8
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_9"
      sld-id: sldl-33GR9
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_10"
      sld-id: sldl-33GR10
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_11"
      sld-id: sldl-33GR11
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_12"
      sld-id: sldl-33GR12
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_13"
      sld-id: sldl-33GR13
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_14"
      sld-id: sldl-33GR14
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_15"
      sld-id: sldl-33GR15
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_16"
      sld-id: sldl-33GR16
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_17"
      sld-id: sldl-33GR17
    - os-id: "ocd-division/country:us/state:nh/sldl:grafton_18"
      sld-id: sldl-33GR18
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_1"
      sld-id: sldl-33HI1
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_2"
      sld-id: sldl-33HI2
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_3"
      sld-id: sldl-33HI03
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_4"
      sld-id: sldl-33HI04
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_5"
      sld-id: sldl-33HI05
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_6"
      sld-id: sldl-33HI06
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_7"
      sld-id: sldl-33HI07
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_8"
      sld-id: sldl-33HI08
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_9"
      sld-id: sldl-33HI09
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_10"
      sld-id: sldl-33HI10
    - os-id: 'ocd-division/country:us/state:nh/sldl:hillsborough_11'
      sld-id: sldl-33HI11
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_12"
      sld-id: sldl-33HI12
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_13"
      sld-id: sldl-33HI13
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_14"
      sld-id: sldl-33HI14
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_15"
      sld-id: sldl-33HI15
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_16"
      sld-id: sldl-33HI16
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_17"
      sld-id: sldl-33HI17
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_18"
      sld-id: sldl-33HI18
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_19"
      sld-id: sldl-33HI19
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_20"
      sld-id: sldl-33HI20
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_21"
      sld-id: sldl-33HI21
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_22"
      sld-id: sldl-33HI22
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_23"
      sld-id: sldl-33HI23
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_24"
      sld-id: sldl-33HI24
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_25"
      sld-id: sldl-33HI25
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_26"
      sld-id: sldl-33HI26
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_27"
      sld-id: sldl-33HI27
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_28"
      sld-id: sldl-33HI28
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_29"
      sld-id: sldl-33HI29
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_30"
      sld-id: sldl-33HI30
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_31"
      sld-id: sldl-33HI31
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_32"
      sld-id: sldl-33HI32
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_33"
      sld-id: sldl-33HI33
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_34"
      sld-id: sldl-33HI34
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_35"
      sld-id: sldl-33HI35
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_36"
      sld-id: sldl-33HI36
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_37"
      sld-id: sldl-33HI37
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_38"
      sld-id: sldl-33HI38
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_39"
      sld-id: sldl-33HI39
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_40"
      sld-id: sldl-33HI40
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_41"
      sld-id: sldl-33HI41
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_42"
      sld-id: sldl-33HI42
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_43"
      sld-id: sldl-33HI43
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_44"
      sld-id: sldl-33HI44
    - os-id: "ocd-division/country:us/state:nh/sldl:hillsborough_45"
      sld-id: sldl-33HI45
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_1"
      sld-id: sldl-33ME1
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_2"
      sld-id: sldl-33ME2
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_3"
      sld-id: sldl-33ME3
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_4"
      sld-id: sldl-33ME4
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_5"
      sld-id: sldl-33ME5
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_6"
      sld-id: sldl-33ME6
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_7"
      sld-id: sldl-33ME7
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_8"
      sld-id: sldl-33ME8
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_9"
      sld-id: sldl-33ME9
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_10"
      sld-id: sldl-33ME10
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_11"
      sld-id: sldl-33ME11
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_12"
      sld-id: sldl-33ME12
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_13"
      sld-id: sldl-33ME13
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_14"
      sld-id: sldl-33ME14
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_15"
      sld-id: sldl-33ME15
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_16"
      sld-id: sldl-33ME16
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_17"
      sld-id: sldl-33ME17
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_18"
      sld-id: sldl-33ME18
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_19"
      sld-id: sldl-33ME19
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_20"
      sld-id: sldl-33ME20
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_21"
      sld-id: sldl-33ME21
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_22"
      sld-id: sldl-33ME22
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_23"
      sld-id: sldl-33ME23
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_24"
      sld-id: sldl-33ME24
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_25"
      sld-id: sldl-33ME25
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_26"
      sld-id: sldl-33ME26
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_27"
      sld-id: sldl-33ME27
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_28"
      sld-id: sldl-33ME28
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_29"
      sld-id: sldl-33ME29
    - os-id: "ocd-division/country:us/state:nh/sldl:merrimack_30"
      sld-id: sldl-33ME30
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_1"
      sld-id: sldl-33RO1
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_2"
      sld-id: sldl-33RO2
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_3"
      sld-id: sldl-33RO3
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_4"
      sld-id: sldl-33RO4
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_5"
      sld-id: sldl-33RO5
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_6"
      sld-id: sldl-33RO6
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_7"
      sld-id: sldl-33RO7
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_8"
      sld-id: sldl-33RO8
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_9"
      sld-id: sldl-33RO9
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_10"
      sld-id: sldl-33RO10
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_11"
      sld-id: sldl-33RO11
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_12"
      sld-id: sldl-33RO12
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_13"
      sld-id: sldl-33RO13
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_14"
      sld-id: sldl-33RO14
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_15"
      sld-id: sldl-33RO15
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_16"
      sld-id: sldl-33RO16
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_17"
      sld-id: sldl-33RO17
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_18"
      sld-id: sldl-33RO18
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_19"
      sld-id: sldl-33RO19
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_20"
      sld-id: sldl-33RO20
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_21"
      sld-id: sldl-33RO21
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_22"
      sld-id: sldl-33RO22
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_23"
      sld-id: sldl-33RO23
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_24"
      sld-id: sldl-33RO24
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_25"
      sld-id: sldl-33RO25
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_26"
      sld-id: sldl-33RO26
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_27"
      sld-id: sldl-33RO27
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_28"
      sld-id: sldl-33RO28
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_29"
      sld-id: sldl-33RO29
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_30"
      sld-id: sldl-33RO30
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_31"
      sld-id: sldl-33RO31
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_32"
      sld-id: sldl-33RO32
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_33"
      sld-id: sldl-33RO33
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_34"
      sld-id: sldl-33RO34
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_35"
      sld-id: sldl-33RO35
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_36"
      sld-id: sldl-33RO36
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_37"
      sld-id: sldl-33RO37
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_38"
      sld-id: sldl-33RO38
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_39"
      sld-id: sldl-33RO39
    - os-id: "ocd-division/country:us/state:nh/sldl:rockingham_40"
      sld-id: sldl-33RO40
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_1"
      sld-id: sldl-33ST1
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_2"
      sld-id: sldl-33ST2
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_3"
      sld-id: sldl-33ST3
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_4"
      sld-id: sldl-33ST4
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_5"
      sld-id: sldl-33ST5
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_6"
      sld-id: sldl-33ST6
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_7"
      sld-id: sldl-33ST7
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_8"
      sld-id: sldl-33ST8
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_9"
      sld-id: sldl-33ST9
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_10"
      sld-id: sldl-33ST10
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_11"
      sld-id: sldl-33ST11
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_12"
      sld-id: sldl-33ST12
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_13"
      sld-id: sldl-33ST13
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_14"
      sld-id: sldl-33ST14
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_15"
      sld-id: sldl-33ST15
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_16"
      sld-id: sldl-33ST16
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_17"
      sld-id: sldl-33ST17
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_18"
      sld-id: sldl-33ST18
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_19"
      sld-id: sldl-33ST19
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_20"
      sld-id: sldl-33ST20
    - os-id: "ocd-division/country:us/state:nh/sldl:strafford_21"
      sld-id: sldl-33ST21
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_1"
      sld-id: sldl-33SU1
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_2"
      sld-id: sldl-33SU2
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_3"
      sld-id: sldl-33SU3
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_4"
      sld-id: sldl-33SU4
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_5"
      sld-id: sldl-33SU5
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_6"
      sld-id: sldl-33SU6
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_7"
      sld-id: sldl-33SU7
    - os-id: "ocd-division/country:us/state:nh/sldl:sullivan_8"
      sld-id: sldl-33SU8
