name: Ohio
os-id-prefix: "ocd-division/country:us/state:oh"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-39([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-390([\d]+)'
  cd:
    key: DISTRICT
    sld-match: 'cd-39([\d]+)'
