name: Oklahoma
shapefile_urls:
  upper: https://thearp.org/documents/886/OK_SD_Enacted11222021.zip
  lower: https://thearp.org/documents/883/OK_LD_Enacted11222021.zip
  congress: https://thearp.org/documents/880/OK_CD_Enacted11222021.zip
id-mappings:
  sldl:
    key: DISTRICT
    os-id-prefix: "ocd-division/country:us/state:ok/sldl:"
    sld-match: 'sldl-40([\d]+)'
  sldu:
    key: DISTRICT
    os-id-prefix: "ocd-division/country:us/state:ok/sldu:"
    sld-match: 'sldu-400([\d]+)'
