name: Oregon
shapefile_urls:
  upper: https://thearp.org/documents/895/OR_SD_Enacted09272021_3XTO7kq.zip
  lower: https://thearp.org/documents/892/OR_LD_Enacted09272021_i0VR2RF.zip
  congress: https://thearp.org/documents/889/OR_CD_Enacted09272021_DoB1jYB.zip
id-mappings:
  sldl:
    key: DISTRICT
    os-id-prefix: "ocd-division/country:us/state:or/sldl:"
    sld-match: 'sldl-410([\d]+)'
  sldu:
    key: DISTRICT
    os-id-prefix: "ocd-division/country:us/state:or/sldu:"
    sld-match: 'sldu-410([\d]+)'
