name: Puerto Rico
id-mappings:
  sldl:
    key: SLDLST
    os-id-prefix: "ocd-division/country:us/territory:pr/sldl:"
    sld-match: 'sldl-720([\d+])'
  sldu:
    os-id-prefix: "ocd-division/country:us/territory:pr/sldu:"
    key: SLDUST
  cd:
    key: SLDUST
    os-id-prefix: "ocd-division/country:us/territory:pr"
    sld-match: 'cd-72([\d]+)'
