name: Puerto Rico
id-mappings:
  sldl:
    key: SLDLST
    os-id-prefix: "ocd-division/country:us/territory:pr"
    sld-match: 'sldl-720([\d+])'
  sldu:
    os-id-prefix: "ocd-division/country:us/territory:pr"
    key: SLDUST
    sld-match: 'sldu-7200(\d)'
  cd:
    key: SLDUST
    os-id-prefix: "ocd-division/country:us/territory:pr"
    sld-match: 'cd-72([\d]+)'
