name: Puerto Rico
os-id-prefix: "ocd-division/country:us/territory:pr"
id-mappings:
  sldl:
    key: SLDUST
    sld-match: 'sldl-720([\d+])'
  sldu:
    key: SLDUST
  cd:
    key: SLDUST
    sld-match: 'sldl-720([\d+])'
    sld-match: 'sldu-7200([\d])'
