name: South Carolina
id-mappings:
  sldl:
    key: ID
    os-id-prefix: "ocd-division/country:us/state:sc/sldl:"
    sld-match: 'sldl-45([\d]+)'
  sldu:
    key: DISTRICT
    os-id-prefix: "ocd-division/country:us/state:sc/sldu:"
    sld-match: 'sldu-450([\d]+)'
shapefile_urls:
  upper: https://thearp.org/documents/929/SC_SD_Enacted_1210201.zip
  lower: https://thearp.org/documents/926/SC_LD_Enacted_1210201.zip
  congress: https://thearp.org/documents/923/SC_CD_Enacted_01262022.zip
