name: Tennessee
os-id-prefix: "ocd-division/country:us/state:tn"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-47([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-470([\d]+)'
  cd:
    key: DISTRICT
