name: Utah
shapefile_urls:
  upper: https://thearp.org/documents/965/UT_SD_Enacted11162021.zip
  lower: https://thearp.org/documents/962/ut_ld_11162021.zip
id-mappings:
  sldl:
    os-id-prefix: "ocd-division/country:us/state:ut/sldl:"
    sld-match: 'sldl-490([\d+])'
  sldu:
    os-id-prefix: "ocd-division/country:us/state:ut/sldu:"
    sld-match: 'sldu-490([\d+])'
