name: Virginia
os-id-prefix: "ocd-division/country:us/state:va"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-51([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-51(\d+)'
  cd:
    key: DISTRICT
    sld-match: 'cd-51([\d]+)'
