name: Vermont
os-id-prefix: "ocd-division/country:us/state:vt"
id-mappings:
  sldl:
    key: DISTRICT
  sldu:
    key: DISTRICT
  cd:
    key: DISTRICT
    sld-match: 'cd-500(\d)'
  custom:
    - os-id: "ocd-division/country:us/state:vt/sldu:addison"
      sld-id: sldu-50ADD
    - os-id: "ocd-division/country:us/state:vt/sldu:bennington"
      sld-id: sldu-50BEN
    - os-id: "ocd-division/country:us/state:vt/sldu:caledonia"
      sld-id: sldu-50CAL
    - os-id: "ocd-division/country:us/state:vt/sldu:grand_isle"
      sld-id: sldu-50GRI
    - os-id: "ocd-division/country:us/state:vt/sldu:chittenden-north"
      sld-id: sldu-50CHN
    - os-id: "ocd-division/country:us/state:vt/sldu:chittenden-central"
      sld-id: sldu-50CHC
    - os-id: "ocd-division/country:us/state:vt/sldu:chittenden-southeast"
      sld-id: sldu-50CHS
    - os-id: "ocd-division/country:us/state:vt/sldu:orleans"
      sld-id: sldu-50ORL
    - os-id: "ocd-division/country:us/state:vt/sldu:essex"
      sld-id: sldu-50ESX
    - os-id: "ocd-division/country:us/state:vt/sldu:franklin"
      sld-id: sldu-50FRA
    - os-id: "ocd-division/country:us/state:vt/sldu:lamoille"
      sld-id: sldu-50LAM
    - os-id: "ocd-division/country:us/state:vt/sldu:orange"
      sld-id: sldu-50ORA
    - os-id: "ocd-division/country:us/state:vt/sldu:rutland"
      sld-id: sldu-50RUT
    - os-id: "ocd-division/country:us/state:vt/sldu:washington"
      sld-id: sldu-50WAS
    - os-id: "ocd-division/country:us/state:vt/sldu:windham"
      sld-id: sldu-50WDH
    - os-id: "ocd-division/country:us/state:vt/sldu:windsor"
      sld-id: sldu-50WSR

    - os-id: "ocd-division/country:us/state:vt/sldl:addison-1"
      sld-id: sldl-50A-1
    - os-id: "ocd-division/country:us/state:vt/sldl:addison-2"
      sld-id: sldl-50A-2
    - os-id: "ocd-division/country:us/state:vt/sldl:addison-3"
      sld-id: sldl-50A-3
    - os-id: "ocd-division/country:us/state:vt/sldl:addison-4"
      sld-id: sldl-50A-4
    - os-id: "ocd-division/country:us/state:vt/sldl:addison-5"
      sld-id: sldl-50A-5
    - os-id: "ocd-division/country:us/state:vt/sldl:addison-rutland"
      sld-id: sldl-50A-R
    - os-id: "ocd-division/country:us/state:vt/sldl:bennington-1"
      sld-id: sldl-50B-1
    - os-id: "ocd-division/country:us/state:vt/sldl:bennington-2"
      sld-id: sldl-50B-2
    - os-id: "ocd-division/country:us/state:vt/sldl:bennington-3"
      sld-id: sldl-50B-3
    - os-id: "ocd-division/country:us/state:vt/sldl:bennington-4"
      sld-id: sldl-50B-4
    - os-id: "ocd-division/country:us/state:vt/sldl:bennington-5"
      sld-id: sldl-50B-5
    - os-id: "ocd-division/country:us/state:vt/sldl:bennington-rutland"
      sld-id: sldl-50B-R
    - os-id: "ocd-division/country:us/state:vt/sldl:caledonia-1"
      sld-id: sldl-50CA1
    - os-id: "ocd-division/country:us/state:vt/sldl:caledonia-2"
      sld-id: sldl-50CA2
    - os-id: "ocd-division/country:us/state:vt/sldl:caledonia-3"
      sld-id: sldl-50CA3
    - os-id: "ocd-division/country:us/state:vt/sldl:caledonia-washington"
      sld-id: sldl-50CAW
    - os-id: "ocd-division/country:us/state:vt/sldl:essex-caledonia"
      sld-id: sldl-50E-C
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-1"
      sld-id: sldl-50F-1
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-2"
      sld-id: sldl-50F-2
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-3"
      sld-id: sldl-50F-3
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-4"
      sld-id: sldl-50F-4
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-5"
      sld-id: sldl-50F-5
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-6"
      sld-id: sldl-50F-6
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-7"
      sld-id: sldl-50F-7
    - os-id: "ocd-division/country:us/state:vt/sldl:franklin-8"
      sld-id: sldl-50F-8
    - os-id: "ocd-division/country:us/state:vt/sldl:grand_isle-chittenden"
      sld-id: sldl-50GIC
    - os-id: "ocd-division/country:us/state:vt/sldl:lamoille-1"
      sld-id: sldl-50L-1
    - os-id: "ocd-division/country:us/state:vt/sldl:lamoille-2"
      sld-id: sldl-50L-2
    - os-id: "ocd-division/country:us/state:vt/sldl:lamoille-3"
      sld-id: sldl-50L-3
    - os-id: "ocd-division/country:us/state:vt/sldl:lamoille-washington"
      sld-id: sldl-50L-W
    - os-id: "ocd-division/country:us/state:vt/sldl:orleans-1"
      sld-id: sldl-50O-1
    - os-id: "ocd-division/country:us/state:vt/sldl:orleans-2"
      sld-id: sldl-50O-2
    - os-id: "ocd-division/country:us/state:vt/sldl:orleans-3"
      sld-id: sldl-50O-3
    - os-id: "ocd-division/country:us/state:vt/sldl:orleans-4"
      sld-id: sldl-50O-4
    - os-id: "ocd-division/country:us/state:vt/sldl:orange-caledonia"
      sld-id: sldl-50ORC
    - os-id: "ocd-division/country:us/state:vt/sldl:orleans-lamoille"
      sld-id: sldl-50O-L
    - os-id: "ocd-division/country:us/state:vt/sldl:orange-1"
      sld-id: sldl-50OR1
    - os-id: "ocd-division/country:us/state:vt/sldl:orange-2"
      sld-id: sldl-50OR2
    - os-id: "ocd-division/country:us/state:vt/sldl:orange-3"
      sld-id: sldl-50OR3
    - os-id: "ocd-division/country:us/state:vt/sldl:orange-washington-addison"
      sld-id: sldl-50OWA
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-1"
      sld-id: sldl-50R-1
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-2"
      sld-id: sldl-50R-2
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-3"
      sld-id: sldl-50R-3
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-4"
      sld-id: sldl-50R-4
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-5"
      sld-id: sldl-50R-5
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-6"
      sld-id: sldl-50R-6
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-7"
      sld-id: sldl-50R-7
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-8"
      sld-id: sldl-50R-8
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-9"
      sld-id: sldl-50R-9
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-10"
      sld-id: sldl-50R10
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-11"
      sld-id: sldl-50R11
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-bennington"
      sld-id: sldl-50R-B
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-1"
      sld-id: sldl-50W-1
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-2"
      sld-id: sldl-50W-2
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-3"
      sld-id: sldl-50W-3
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-4"
      sld-id: sldl-50W-4
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-5"
      sld-id: sldl-50W-5
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-6"
      sld-id: sldl-50W-6
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-7"
      sld-id: sldl-50W-7
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-8"
      sld-id: sldl-50W-8
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-9"
      sld-id: sldl-50W-9
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-1"
      sld-id: sldl-50WA1
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-2"
      sld-id: sldl-50WA2
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-3"
      sld-id: sldl-50WA3
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-4"
      sld-id: sldl-50WA4
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-5"
      sld-id: sldl-50WA5
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-6"
      sld-id: sldl-50WA6
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-chittenden"
      sld-id: sldl-50WAC
    - os-id: "ocd-division/country:us/state:vt/sldl:windham-bennington-windsor"
      sld-id: sldl-50WWB
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-1"
      sld-id: sldl-50Y-1
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-2"
      sld-id: sldl-50Y-2
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-3"
      sld-id: sldl-50Y-3
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-4"
      sld-id: sldl-50Y-4
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-5"
      sld-id: sldl-50Y-5
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-6"
      sld-id: sldl-50Y-6
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-orange-1"
      sld-id: sldl-50YO1
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-orange-2"
      sld-id: sldl-50YO2
    - os-id: "ocd-division/country:us/state:vt/sldl:essex-orleans"
      sld-id: sldl-50E-O
    - os-id: "ocd-division/country:us/state:vt/sldl:caledonia-essex"
      sld-id: sldl-50CAE
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-franklin"
      sld-id: sldl-50C-F
    - os-id: "ocd-division/country:us/state:vt/sldl:washington-orange"
      sld-id: sldl-50WAO
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-1"
      sld-id: sldl-50C-1
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-2"
      sld-id: sldl-50C-2
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-3"
      sld-id: sldl-50C-3
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-4"
      sld-id: sldl-50C-4
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-5"
      sld-id: sldl-50C-5
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-6"
      sld-id: sldl-50C-6
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-7"
      sld-id: sldl-50C-7
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-8"
      sld-id: sldl-50C-8
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-9"
      sld-id: sldl-50C-9
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-10"
      sld-id: sldl-50C10
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-11"
      sld-id: sldl-50C11
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-12"
      sld-id: sldl-50C12
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-13"
      sld-id: sldl-50C13
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-14"
      sld-id: sldl-50C14
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-15"
      sld-id: sldl-50C15
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-16"
      sld-id: sldl-50C16
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-17"
      sld-id: sldl-50C17
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-18"
      sld-id: sldl-50C18
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-19"
      sld-id: sldl-50C19
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-20"
      sld-id: sldl-50C20
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-21"
      sld-id: sldl-50C21
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-22"
      sld-id: sldl-50C22
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-23"
      sld-id: sldl-50C23
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-24"
      sld-id: sldl-50C24
    - os-id: "ocd-division/country:us/state:vt/sldl:chittenden-25"
      sld-id: sldl-50C25
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-addison"
      sld-id: sldl-50Y-A
    - os-id: "ocd-division/country:us/state:vt/sldl:rutland-windsor"
      sld-id: sldl-50R-W
    - os-id: "ocd-division/country:us/state:vt/sldl:windsor-windham"
      sld-id: sldl-50Y-W
