YEAR: 2022

SKIPPED_GEOIDS:
  cd-6098: American Samoa
  cd-6998: Northern Mariana Islands
  cd-6698: Guam
  cd-7898: Virgin Islands

MTFCC_MAPPING:
  G5200: cd
  G5210: sldu
  G5220: sldl

ARP_DIST_MAPPING:
  Leg_Upper: sldu
  Leg_Lower: sldl
  US_Cong: cd

us_cd_file: tl_2022_us_cd116.geojson
