name: Build and push Docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  publish:
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          tags: "openstates/geo:latest,openstates/geo:${{ github.ref_name }}"
          platforms: amd64,arm64
          push: true
    runs-on: ubuntu-latest
